version: "3.9"

services:
  ekklesia:
    build: .
    image: ekklesia
    container_name: ekklesia
    command: go run cmd/ekklesia/main.go
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    ports:
      - "8080:80"
    environment:
      PORT: 80
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ekklesia
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    image: postgres:16.0-alpine
    hostname: db
    container_name: ekklesia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ekklesia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: