version: "3.9"

services:
  ekklesia:
    build: .
    image: ekklesia
    container_name: ekklesia
    command: go run main.go
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    ports:
      - "8080:80"
